name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Format
      run: cargo fmt -- --check
    - name: Check
      run: cargo fmt --tests --features http-ureq -- --check
    - name: Clippy
      run: cargo clippy --no-dpes --features http-ureq
    - name: Run tests
      run: cargo test --verbose --features http-ureq
